### ISSUE TITLE
Цена в рублях и расстояние в км (должно быть int)

### ISSUE THREAD

**Issue by coursar** [AleksandrNagovitsyn/Taxi-application#2]
https://github.com/AleksandrNagovitsyn/Taxi-application/blob/aa67a2805d305b77f7dd0d492eec56961d8f2270/src/main/java/TripCalculator.java#L2

**Comment by AleksandrNagovitsyn** [comment]
@coursar если пассажир проедет 1,01 км и 2 км цена будет одинаковая, а разница в расстоянии ощутимая. Может расстояние оставить в double? Цену к int приведу
